### ISSUE TITLE
about use spotify openapi as demo

### ISSUE THREAD

**Issue by naivefun** [sonallux/spotify-web-api#231]
hi Jonas, sorry I use issues for this request since I cannot find a way to contact you.

Thanks for your work on spotify openapi spec.

We are doing an API collaboration service and we have implemented visual editor for openapi paths and components.

We will launch our service in the next a few months and we will be showing an image of editor on landing page. Becos our team think spotify spec is well maintained we would love to use it for our demo image, if that is ok for you.

The attached is a prototype for your reference.

![image](https://user-images.githubusercontent.com/10683378/222605025-f117ced9-1002-4e69-af90-1eb2ff1bd198.png)

Please let us know what you think, thanks.

**Comment by sonallux** [comment]
Hi, thanks for your request. Sure, for me it is ok, that you use the Spotify spec. But please keep in mind this does not include permission from Spotify itself because I have no affiliation with Spotify nor am I an employee.

**Comment by naivefun** [comment]
@sonallux  thanks, we will proceed :)
