### ISSUE TITLE
`SimplifiedTrackObject` missing `album` property

### ISSUE THREAD

**Issue by peduarte** [sonallux/spotify-web-api#238]
Hey 👋 

Thanks for this project! 

I've noticed that the `SimplifiedTrackObject` is missing an `album` property (`SimplifiedAlbumObject`).

I've manually added on my local version (line ~5382):
```yml
    SimplifiedTrackObject:
      type: object
      x-spotify-docs-type: SimplifiedTrackObject
      properties:
        album:
          allOf:
          - $ref: '#/components/schemas/SimplifiedAlbumObject'
          description: Information about the album.
```

It's also missing from the official definition from Spotify. 

Is it worth adding it to your fixed version?

I read your comment on https://github.com/sonallux/spotify-web-api/issues/114 and seems that we should start using the official Open API definition. Will you keep maintaining this version though while the official one has some mistakes?

Thank you again

**Comment by peduarte** [comment]
Thanks for letting me know. I've never worked with Open API definitions before, and must say, I'm a little scared to make changes haha

**Comment by sonallux** [comment]
@peduarte I have tried to reproduce your issue. Unfortunately, I did not find any usages of the `SimplifiedTrackObject` where the `album` property is missing. In the latest version of my fixed OpenAPI definition the `SimplifiedTrackObject` is only contained in the response of [Get Album Tracks](https://developer.spotify.com/documentation/web-api/reference/get-an-albums-tracks) and [Get Album](https://developer.spotify.com/documentation/web-api/reference/get-an-album). Therefore I am closing this issue. If you still think there is an issue, please provide more information so I can reproduce it.

**Comment by peduarte** [comment]
Ok I'll check out the latest version :)
