### ISSUE TITLE
Rename fixed-spotify.yml to fixed-spotify.yaml

### ISSUE THREAD

**Issue by Flajt** [sonallux/spotify-web-api#252]
Hello, first of all, thanks for this open API spec. 
I'm currently using [this](https://pub.dev/packages/swagger_dart_code_generator) tool to generate a dart lib for it.

They offer support to pull the specs directly via URL, however, there seems to be an issue with the .yml extension (idk why), so I wanted to ask if you could change the extension for the output file to ".yaml"?

It's just a convenience feature so if not also no problem.

**Comment by sonallux** [comment]
Hi @Flajt, thanks for opening an issue. I think this is more of an issue with your tool. Have you opened an issue on their [Issue tracker](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/issues) ?

**Comment by Flajt** [comment]
For this no, but I can do that if you think that is better.

**Comment by sonallux** [comment]
Yes, I think the tool should be capable of handling `*.yaml` und `*.yml` files.
