### ISSUE TITLE
Missing content type in outputted yml.

### ISSUE THREAD

**Issue by DDtMM** [sonallux/spotify-web-api#80]
For **endpoint-reorder-or-replace-playlists-tracks**
Line **4108**

The 201 response for endpoint-reorder-or-replace-playlists-tracks has no content, therefore the default content of the error response is used.  It should be SnapshotIdObject:

```
       content:
            application/json:
              schema:
                $ref: '#/components/schemas/SnapshotIdObject'
```

I haven't done Java in a while, but it looks like _EndpointSplitter.java_ line 133  should be changed, replacing **Void** with **SnapshotIdObject**:
```
    List.of(new SpotifyWebApiEndpoint.ResponseType("SnapshotIdObject", 201, null))
```

**Comment by sonallux** [comment]
The issue here is, that the 201 response actually contains a `SnapshotIdObject` and not no-content. 

I have a fix ready, that I will release later today.
