### ISSUE TITLE
Incorrect Response for Get Recommendations EndPoint

### ISSUE THREAD

**Issue by DDtMM** [sonallux/spotify-web-api#82]
The documentation for Get Recommendations states that the response tracks array returns a SimplifiedTrackObject.  From experience I see that it returns a TrackObject instead - that is it has the albums and popularity properties.

https://github.com/sonallux/spotify-web-api/blob/c38c5c896e5a9da2426bfbd9743860b0a2ebe9e5/spotify-web-api-generator-open-api/spotify-web-api-openapi.yml#L6858

**Comment by sonallux** [comment]
Thanks for reporting this issue. I also just checked and the get recommendations endpoint is indeed returning the full TrackObject and not a SimplifiedTrackObject even though it is documented that way in the [Web API Reference](https://developer.spotify.com/documentation/web-api/reference/#object-recommendationsobject).

I am going to provide a fix for this.
